In [14]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('jobclassinfo2.csv')
print(data.shape)
data.head(20)

(66, 14)


ID  JobFamily      JobFamilyDescription  JobClass  \
0    1          1    Accounting And Finance         1   
1    2          1    Accounting And Finance         2   
2    3          1    Accounting And Finance         3   
3    4          1    Accounting And Finance         4   
4    5          2    Administrative Support         5   
5    6          2    Administrative Support         6   
6    7          2    Administrative Support         7   
7    8          2    Administrative Support         8   
8    9          2    Administrative Support         9   
9   10          3                     Baker        10   
10  11          3                     Baker        11   
11  12          3                     Baker        12   
12  13          4  Buildings And Facilities        13   
13  14          4  Buildings And Facilities        14   
14  15          4  Buildings And Facilities        15   
15  16          4  Buildings And Facilities        16   
16  17          4  Buildings And Facilities        44   
17  18          4  Buildings And Facilities        45   
18  19          4  Buildings And Facilities        46   
19  20          4  Buildings And Facilities        47   

          JobClassDescription  PayGrade  EducationLevel  Experience  \
0                Accountant I         5               3           1   
1               Accountant II         6               4           1   
2              Accountant III         8               4           2   
3               Accountant IV        10               5           5   
4             Admin Support I         1               1           0   
5            Admin Support II         2               1           1   
6           Admin Support III         3               1           2   
7   Administrative Support IV         4               4           0   
8    Administrative Support V         5               4           0   
9                     Baker I         4               2           0   
10                   Baker II         6               2           0   
11                  Baker III         9               2           0   
12               Facilities I         5               1           0   
13              Facilities II         6               3           0   
14             Facilities III         9               4           0   
15              Facilities IV        10               5           0   
16     Maintenance Services I         2               1           0   
17    Maintenance Services II         3               1           1   
18   Maintenance Services III         4               1           1   
19    Maintenance Services IV         5               3           2   

    OrgImpact  ProblemSolving  Supervision  ContactLevel  FinancialBudget  \
0           3               3            4             3                5   
1           5               4            5             7                7   
2           6               5            6             7               10   
3           6               6            7             8               11   
4           1               1            1             1                1   
5           1               1            1             2                3   
6           1               2            1             3                3   
7           1               2            1             3                5   
8           4               3            5             7                7   
9           1               4            1             1                2   
10          3               4            1             6                4   
11          4               5            5             6               10   
12          3               4            3             7                4   
13          3               4            5             6                7   
14          4               5            7             6               10   
15          6               6            7             8               11   
16   

In [15]:
data.isnull().sum()

ID                      0
JobFamily               0
JobFamilyDescription    0
JobClass                0
JobClassDescription     0
PayGrade                0
EducationLevel          0
Experience              0
OrgImpact               0
ProblemSolving          0
Supervision             0
ContactLevel            0
FinancialBudget         0
PG                      0
dtype: int64

In [16]:
data.describe()

ID  JobFamily   JobClass   PayGrade  EducationLevel  Experience  \
count  66.000000  66.000000  66.000000  66.000000       66.000000   66.000000   
mean   33.500000   7.606061  33.500000   5.696970        3.166667    1.757576   
std    19.196354   4.209436  19.196354   2.517445        1.525005    2.134411   
min     1.000000   1.000000   1.000000   1.000000        1.000000    0.000000   
25%    17.250000   4.000000  17.250000   4.000000        2.000000    0.000000   
50%    33.500000   7.000000  33.500000   5.000000        4.000000    1.000000   
75%    49.750000  11.000000  49.750000   8.000000        4.000000    2.750000   
max    66.000000  15.000000  66.000000  10.000000        6.000000   10.000000   

       OrgImpact  ProblemSolving  Supervision  ContactLevel  FinancialBudget  
count  66.000000       66.000000    66.000000     66.000000        66.000000  
mean    3.348485        3.606061     3.863636      4.757576         5.303030  
std     1.767157        1.412894     2.104109      2.468638         3.525597  
min     1.000000        1.000000     1.000000      1.000000         1.000000  
25%     2.000000        3.000000     1.000000      3.000000         2.000000  
50%     3.000000        4.000000     4.000000      6.000000         5.000000  
75%     4.000000        5.000000     5.750000      7.000000         7.750000  
max     6.000000        6.000000     7.000000      8.000000        11.000000

In [17]:
object_type_features = data.select_dtypes("object").columns
object_type_features

Index(['JobFamilyDescription', 'JobClassDescription', 'PG'], dtype='object')

In [18]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

for feat_name in object_type_features: 
    data[feat_name] = le.fit_transform(data[feat_name])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 14 columns):
ID                      66 non-null int64
JobFamily               66 non-null int64
JobFamilyDescription    66 non-null int32
JobClass                66 non-null int64
JobClassDescription     66 non-null int32
PayGrade                66 non-null int64
EducationLevel          66 non-null int64
Experience              66 non-null int64
OrgImpact               66 non-null int64
ProblemSolving          66 non-null int64
Supervision             66 non-null int64
ContactLevel            66 non-null int64
FinancialBudget         66 non-null int64
PG                      66 non-null int32
dtypes: int32(3), int64(11)
memory usage: 6.5 KB


In [19]:
le.inverse_transform(data['PG'])

array(['PG05', 'PG06', 'PG08', 'PG10', 'PG01', 'PG02', 'PG03', 'PG04',
       'PG05', 'PG04', 'PG06', 'PG09', 'PG05', 'PG06', 'PG09', 'PG10',
       'PG02', 'PG03', 'PG04', 'PG05', 'PG05', 'PG08', 'PG09', 'PG01',
       'PG03', 'PG06', 'PG04', 'PG05', 'PG08', 'PG02', 'PG03', 'PG05',
       'PG07', 'PG02', 'PG04', 'PG05', 'PG10', 'PG02', 'PG04', 'PG05',
       'PG08', 'PG05', 'PG06', 'PG09', 'PG05', 'PG07', 'PG08', 'PG05',
       'PG07', 'PG09', 'PG10', 'PG03', 'PG06', 'PG07', 'PG09', 'PG10',
       'PG03', 'PG05', 'PG04', 'PG05', 'PG08', 'PG03', 'PG05', 'PG06',
       'PG08', 'PG10'], dtype=object)

In [20]:
data.head()

ID  JobFamily  JobFamilyDescription  JobClass  JobClassDescription  \
0   1          1                     0         1                    0   
1   2          1                     0         2                    1   
2   3          1                     0         3                    2   
3   4          1                     0         4                    3   
4   5          2                     1         5                    4   

   PayGrade  EducationLevel  Experience  OrgImpact  ProblemSolving  \
0         5               3           1          3               3   
1         6               4           1          5               4   
2         8               4           2          6               5   
3        10               5           5          6               6   
4         1               1           0          1               1   

   Supervision  ContactLevel  FinancialBudget  PG  
0            4             3                5   4  
1            5             7                7   5  
2            6             7               10   7  
3            7             8               11   9  
4            1             1                1   0

In [21]:
data["PG"] += 1
data.head()

ID  JobFamily  JobFamilyDescription  JobClass  JobClassDescription  \
0   1          1                     0         1                    0   
1   2          1                     0         2                    1   
2   3          1                     0         3                    2   
3   4          1                     0         4                    3   
4   5          2                     1         5                    4   

   PayGrade  EducationLevel  Experience  OrgImpact  ProblemSolving  \
0         5               3           1          3               3   
1         6               4           1          5               4   
2         8               4           2          6               5   
3        10               5           5          6               6   
4         1               1           0          1               1   

   Supervision  ContactLevel  FinancialBudget  PG  
0            4             3                5   5  
1            5             7                7   6  
2            6             7               10   8  
3            7             8               11  10  
4            1             1                1   1

In [22]:
data.drop(['ID'], axis = 1, inplace = True)

In [23]:
X = data.drop("PG",axis=1)
y = data["PG"]

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=2)

In [41]:
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

C:\Users\SAYTECH\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [42]:
predictions = logmodel.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.2857142857142857

In [44]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()

DT.fit(X_train, y_train)
pred_dt = DT.predict(X_test)

In [45]:
accuracy_score(y_test,pred_dt)

1.0

In [46]:
print(f"Unique FN: {data['PG'].unique()}")

Unique FN: [ 5  6  8 10  1  2  3  4  9  7]


In [47]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
 
knn.fit(X_train, y_train)

print(knn.score(X_test, y_test))

0.0


In [48]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)
expected = y
predicted = model.predict(X)
accuracy_score(expected, predicted)

1.0

In [51]:
data.head(15)

JobFamily  JobFamilyDescription  JobClass  JobClassDescription  PayGrade  \
0           1                     0         1                    0         5   
1           1                     0         2                    1         6   
2           1                     0         3                    2         8   
3           1                     0         4                    3        10   
4           2                     1         5                    4         1   
5           2                     1         6                    5         2   
6           2                     1         7                    6         3   
7           2                     1         8                    7         4   
8           2                     1         9                    8         5   
9           3                     2        10                    9         4   
10          3                     2        11                   10         6   
11          3                     2        12                   11         9   
12          4                     3        13                   22         5   
13          4                     3        14                   23         6   
14          4                     3        15                   24         9   

    EducationLevel  Experience  OrgImpact  ProblemSolving  Supervision  \
0                3           1          3               3            4   
1                4           1          5               4            5   
2                4           2          6               5            6   
3                5           5          6               6            7   
4                1           0          1               1            1   
5                1           1          1               1            1   
6                1           2          1               2            1   
7                4           0          1               2            1   
8                4           0          4               3            5   
9                2           0          1               4            1   
10               2           0          3               4            1   
11               2           0          4               5            5   
12               1           0          3               4            3   
13               3           0          3               4            5   
14               4           0          4               5            7   

    ContactLevel  FinancialBudget  PG  
0              3                5   5  
1              7                7   6  
2              7               10   8  
3              8               11  10  
4              1                1   1  
5              2                3   2  
6              3                3   3  
7              3                5   4  
8              7                7   5  
9              1                2   4  
10             6                4   6  
11             6               10   9  
12             7                4   5  
13             6                7   6  
14             6               10   9

In [54]:
Xnew = ([[1 ,1, 10, 8, 7, 4, 1, 2, 3, 5, 4, 7],
        [1, 0, 1, 0, 5, 3, 1, 3, 3, 4, 3, 5]])

DT.predict(Xnew)

C:\Users\SAYTECH\Anaconda3\lib\site-packages\sklearn\base.py:446: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([7, 5])

In [56]:
logmodel.predict(Xnew)

C:\Users\SAYTECH\Anaconda3\lib\site-packages\sklearn\base.py:446: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


array([9, 5])

In [22]:
Xnew = ([[2, 1, 8, 7, 4, 4, 0, 1, 2, 1, 3, 5],
        [3, 2, 10, 9, 4, 2, 0, 1, 4, 1, 1, 2]])

DT.predict(Xnew)

array([4, 4])

In [57]:
model.predict(Xnew)

C:\Users\SAYTECH\Anaconda3\lib\site-packages\sklearn\base.py:446: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"


array([7, 5])

In [24]:
data.head(10)

JobFamily  JobFamilyDescription  JobClass  JobClassDescription  PayGrade  \
0          1                     0         1                    0         5   
1          1                     0         2                    1         6   
2          1                     0         3                    2         8   
3          1                     0         4                    3        10   
4          2                     1         5                    4         1   
5          2                     1         6                    5         2   
6          2                     1         7                    6         3   
7          2                     1         8                    7         4   
8          2                     1         9                    8         5   
9          3                     2        10                    9         4   

   EducationLevel  Experience  OrgImpact  ProblemSolving  Supervision  \
0               3           1          3               3            4   
1               4           1          5               4            5   
2               4           2          6               5            6   
3               5           5          6               6            7   
4               1           0          1               1            1   
5               1           1          1               1            1   
6               1           2          1               2            1   
7               4           0          1               2            1   
8               4           0          4               3            5   
9               2           0          1               4            1   

   ContactLevel  FinancialBudget  PG  
0             3                5   5  
1             7                7   6  
2             7               10   8  
3             8               11  10  
4             1                1   1  
5             2                3   2  
6             3                3   3  
7             3                5   4  
8             7                7   5  
9             1                2   4